name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_release:
    name: "Build and Release"
    strategy:
      matrix:
        os: [windows-latest]
        # os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install dependencies (linux)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt update && sudo apt install -y ninja-build patchelf
    
    - name: Install Ninja (windows)
      if: matrix.os == 'windows-latest'
      run: choco install ninja
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.1'
    
    - name: Configure MSVC (windows)
      uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest'
    
    - name: Configure and build
      run: |
        cmake -S . -B build -G "Ninja Multi-Config"
        cmake --build build --config Release

    - name: Package Windows App
      if: matrix.os == 'windows-latest'
      run: |
        windeployqt --release --dir viewer3D build\Release\appViewer3D.exe
        cd viewer3D
        7z a ../viewer3D.zip *
      shell: cmd
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"

    - name: Get current date
      id: date
      run: echo "tag=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV
      shell: bash
    
    - name: Create and Push Git Tag
      run: |
        git tag ${{ env.tag }}
        git push https://${{ secrets.PAT_GITHUB }}@github.com/${{ github.repository }}.git ${{ env.tag }}


    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.tag }}
        files: |
          viewer3D.zip
          # viewer3D.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
