name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_release:
    name: "Build and Release"
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Ninja (windows)
      if: matrix.os == 'windows-latest'
      run: choco install ninja
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.1'
    
    - name: Configure MSVC (windows)
      uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest'
    
    - name: Configure and build
      run: |
        cmake -S . -B build -G "Ninja Multi-Config"
        cmake --build build --config Release

    - name: Check Release folder
      run: |
        echo "Contents of build/Release:"
        Get-ChildItem -Path build/Release
        echo "Contents of build/Viewer3D:"
        Get-ChildItem -Path build/Viewer3D
      shell: pwsh

    - name: Package Windows App
      if: matrix.os == 'windows-latest'
      run: |
        $Env:Path += ";$Env{Qt6_DIR}\bin"
        windeployqt6 --release build/Release/appViewer3D.exe
      shell: pwsh

    - name: Copy QML files
      run: |
        mkdir -p build/Release/qml
        cp -r build/Viewer3D/*.qml build/Release/qml/
        cp -r build/Viewer3D/qmldir build/Release/qml/
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: viewer3D
        path: |
          build/Release/
          build/Release/qml/
    
