name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_release:
    name: "Build and Release"
    strategy:
      matrix:
        os: [windows-latest]
        # os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install dependencies (linux)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt update && sudo apt install -y ninja-build patchelf
    
    - name: Install Ninja (windows)
      if: matrix.os == 'windows-latest'
      run: choco install ninja
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.1'
    
    - name: Configure MSVC (windows)
      uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest'
    
    - name: Configure and build
      run: |
        cmake -S . -B build -G "Ninja Multi-Config"
        cmake --build build --config Release

    - name: Check Release folder
      run: |
        dir Build\Release
        dir D:\a\Viewer3D\Viewer3D\build\Viewer3D

    - name: Package Windows App
      if: matrix.os == 'windows-latest'
      run: |
        windeployqt6 --release Build\Release\appViewer3D.exe
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: viewer3D
        path: Build\Release/
    
    
        
